name: destroy terraform resources

on:
  workflow_dispatch: 

jobs:
    terraform:
        runs-on: ubuntu-latest

        env:
            terraform_version: 1.5.1
            AWS_REGION: us-east-1
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: ${{ env.terraform_version }}
        - name: Terraform Init
          run: terraform init
        - name: Terraform Destroy
          run: terraform destroy -auto-approve